[package]
name = "observer"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["json"] }
tokio = { version = "1.0", features = ["io-std", "macros", "rt-multi-thread", "time"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
call-agent = "1.2.3"
chrono-tz = "0.10.1"
playwright = "0.0.20"
dashmap = "6.1.0"
log = "0.4.25"
env_logger = "0.11.6"
chrono = { version = "0.4", features = ["serde"] }
regex = "1.11.1"
cron = "0.15.0"
urlencoding = "2.1.3"
scraper = "0.22.0"
lazy_static = "1.4"
serenity = { version = "0.12", features = ["client", "gateway", "rustls_backend"] }
actix-web = "4.9.0"

[patch.crates-io]
call-agent = { path = "I:/RustBuilds/call-agent" }

[profile.release]
opt-level = 3  # サイズを最小化するための最適化
lto = true       # リンクタイム最適化を有効にする
panic = "abort"  # パニック時にアボートする
strip = true     # デバッグ情報を削除する